---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  namespace: denostr
  name: denostr-static-mirroring-statefulset
  labels:
    component: denostr
spec:
  serviceName: denostr-svc
  replicas: 1
  selector:
    matchLabels:
      component: denostr
  template:
    metadata:
      labels:
        component: denostr
    spec:
      imagePullSecrets:
        - name: ghcr
      containers:
        - name: relay
          image: ghcr.io/guakamoli/denostr:next-static-mirroring
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              cpu: "100m"
              memory: "100Mi"
            limits:
              cpu: "500m"
              memory: "500Mi"
          env:
            - name: MONGO_URI
              value: "mongodb://user:pass@host:port/db?replicaSet=rs0&authSource=admin"
            - name: SECRET
              value: 1234567890abcdefghijklmnopqrstuvwxyz
            - name: WORKER_TYPE
              value: maintenance
          ports:
            - containerPort: 8008
              name: ws
          volumeMounts:
            - mountPath: /app/.nostr
              name: denostr-config-val
      volumes:
        - name: denostr-config-val
          configMap:
            name: denostr-config
            items:
            - key: settings.yaml
              path: settings.yaml

---
apiVersion: v1
data:
  settings.yaml: |
    info:
      relay_url: ws://your-domain.com
      name: "nostr relay by denostr"
      description: Deno based, cloud native nostr implemention support by ByteTrade
      pubkey: replace-with-your-pubkey-in-hex
      contact: operator@your-domain.com
    payments:
      enabled: false
      processor: zebedee
      feeSchedules:
        admission:
        - enabled: false
          description: Admission fee charged per public key in msats (1000 msats = 1 satoshi)
          amount: 1000000
          whitelists:
            pubkeys:
              - replace-with-your-pubkey-in-hex
              # Allow the following Zap providers:
              # LightningTipBot by Calle
              - "fcd720c38d9ee337188f47aac845dcd8f590ccdb4a928b76dde18187b4c9d37d"
    paymentsProcessors:
      zebedee:
        baseURL: https://api.zebedee.io/
        callbackBaseURL: https://denostr.your-domain.com/callbacks/zebedee
        ipWhitelist:
          - "3.225.112.64"
          - "::ffff:3.225.112.64"
      lnbits:
        baseURL: https://lnbits.your-domain.com/
        callbackBaseURL: https://denostr.your-domain.com/callbacks/lnbits
    network:
      maxPayloadSize: 524288
      # Comment the next line if using CloudFlare proxy
      remoteIpHeader: x-forwarded-for
      # Uncomment the next line if using CloudFlare proxy
      # remoteIpHeader: cf-connecting-ip
    workers:
      count: 1
    mirroring:
      static: []
    limits:
      invoice:
        rateLimits:
        - period: 60000
          rate: 12
        - period: 3600000
          rate: 30
        ipWhitelist:
        - "::1"
        - "10.10.10.1"
        - "::ffff:10.10.10.1"
      connection:
        rateLimits:
        - period: 1000
          rate: 24
        - period: 60000
          rate: 72
        ipWhitelist:
        - "::1"
        - "10.10.10.1"
        - "::ffff:10.10.10.1"
      event:
        eventId:
          minLeadingZeroBits: 0
        kind:
          whitelist: []
          blacklist: []
        pubkey:
          minBalance: 0
          minLeadingZeroBits: 0
          whitelist: []
          blacklist: []
        createdAt:
          maxPositiveDelta: 900
          maxNegativeDelta: 0
        content:
        - description: 64 KB for event kind ranges 0-10 and 40-49
          kinds:
          - - 0
            - 10
          - - 40
            - 49
          maxLength: 65536
        - description: 96 KB for event kind ranges 11-39 and 50-max
          kinds:
          - - 11
            - 39
          - - 50
            - 9007199254740991
          maxLength: 98304
        rateLimits:
        - description: 10 events/min for event kinds 0, 3, 40 and 41
          kinds:
          - 0
          - 3
          - 40
          - 41
          period: 60000
          rate: 10
        - description: 16 events/min for event kinds 1, 2, 4 and 42
          kinds:
          - 1
          - 2
          - 4
          - 42
          period: 60000
          rate: 16
        - description: 30 events/min for event kind ranges 5-7 and 43-49
          kinds:
          - - 5
            - 7
          - - 43
            - 49
          period: 60000
          rate: 30
        - description: 24 events/min for replaceable events and parameterized replaceable
            events
          kinds:
          - - 10000
            - 19999
          - - 30000
            - 39999
          period: 60000
          rate: 24
        - description: 60 events/min for ephemeral events
          kinds:
          - - 20000
            - 29999
          period: 60000
          rate: 60
        - description: 720 events/hour for all events
          period: 3600000
          rate: 720
        whitelists:
          pubkeys: []
          ipAddresses:
          - "::1"
          - "10.10.10.1"
          - "::ffff:10.10.10.1"
      client:
        subscription:
          maxSubscriptions: 10
          maxFilters: 10
      message:
        rateLimits:
        - description: 240 raw messages/min
          period: 60000
          rate: 240
        ipWhitelist:
        - "::1"
        - "10.10.10.1"
        - "::ffff:10.10.10.1"
kind: ConfigMap
metadata:
  labels:
    component: denostr
  name: denostr-config
  namespace: denostr
